In [14]:
pip install openpyxl

527.03s - pydevd: Sending message related to process being replaced timed-out after 5 seconds

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-1.1.0-py3-none-any.whl.metadata (1.8 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 250.9/250.9 kB 2.1 MB/s eta 0:00:0000:0100:01
Downloading et_xmlfile-1.1.0-py3-none-any.whl (4.7 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-1.1.0 openpyxl-3.1.5
Note: you may need to restart the kernel to use updated packages.

In [7]:
pip install pandas

252.29s - pydevd: Sending message related to process being replaced timed-out after 5 seconds

Collecting pandas
  Downloading pandas-2.2.2-cp312-cp312-macosx_11_0_arm64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=1.26.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Collecting pytz>=2020.1 (from pandas)
  Downloading pytz-2024.1-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas)
  Downloading tzdata-2024.1-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Downloading pandas-2.2.2-cp312-cp312-macosx_11_0_arm64.whl (11.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.3/11.3 MB 744.2 kB/s eta 0:00:0000:0100:01
Downloading pytz-2024.1-py2.py3-none-any.whl (505 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 505.5/505.5 kB 1.5 MB/s eta 0:00:0000:0100:01
Downloading tzdata-2024.1-py2.py3-none-any.whl (345 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 345.4/345.4 kB 1.3 MB/s eta 0:00:0000:0100:01
Installing collected packages: pytz, tzdata, pandas
Successfully installed pandas-2.2.2 pytz-2024.1 tzdata-2024.1
Note: you may need to restart the kernel to use updated packages.

In [15]:
import numpy as np
import pandas as pd

In [16]:
df = pd.read_excel('Attendance Sheet 2022-2023_Masked.xlsx')

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)

In [23]:
df.head(10)

,AtliQ,Unnamed: 1,2022-06-01 00:00:00,2022-06-02 00:00:00,2022-06-03 00:00:00,2022-06-04 00:00:00,2022-06-05 00:00:00,2022-06-06 00:00:00,2022-06-07 00:00:00,2022-06-08 00:00:00,...,Work from home,Paid Leave,Sick Leave,Birthday Leave,Floting festival leave,Bereavement Leave,Leave without pay,Weekly Off,Holidays Off,Menstrual Leave
0,Employee Code,Name,2022-06-01 00:00:00,2022-06-02 00:00:00,2022-06-03 00:00:00,2022-06-04 00:00:00,2022-06-05 00:00:00,2022-06-06 00:00:00,2022-06-07 00:00:00,2022-06-08 00:00:00,...,WFH,PL,SL,BL,FFL,BRL,LWP,WO,HO,ML
1,Atq -406,Thanos Thakur,P,P,P,WO,WO,P,P,P,...,0,0,0,0,0,0,0,8,0,0
2,Atq -462,Jarvis Singh,P,P,P,WO,WO,P,P,P,...,0,0,0,0,0,0,0,8,0,0
3,Atq -411,Nevaeh Waller,P,P,P,WO,WO,P,P,P,...,0,0,0,0,0,0,0,8,0,0
4,Atq -398,Bo Cordova,SL,P,P,WO,WO,P,P,P,...,12,0,1,0,0,0,0,8,0,0
5,Atq -438,Mekhi Singleton,P,P,P,WO,WO,P,P,P,...,0,1,0,0,0,0,0,8,0,0
6,Atq -366,Peter Pandey,P,P,P,WO,WO,P,P,P,...,0,0,0,0,0,0,0,8,0,0
7,Atq -441,Loki Lal,P,P,P,WO,WO,P,P,P,...,0,0,0,0,0,0,0,8,0,0
8,Atq -436,Phoenix Brady,P,P,P,WO,WO,P,P,P,...,0,2,0,0,0,0,0,8,0,0
9,Atq -404,Ana Little,PL,P,P,WO,WO,P,P,P,...,0,3.5,0,0,0,0,0,8,0,0

In [27]:
df.shape

(84, 45)

In [28]:
df.size

3780

## Working prefrence of people